# -*- coding: utf-8 -*-
"""Anandhu Pie and Line.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pCfeLe-3HT84vxYzkfXuBpuDYF2d-F2
"""

#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Reading the data
data = pd.read_csv('/content/world_population.csv')
data

data.isna().sum()

#Grouping the count of continents
data['Continent'].value_counts()

#Plotting the graph
plt.figure(figsize=(15,15))
data.groupby('Continent').size().plot(kind='pie', autopct='%.2f%%')
plt.ylabel('Population Of Continents') 
plt.legend()

"""**Line Plot**"""

#Reading the data
data = pd.read_csv('/content/district wise rainfall normal.csv')
data.head(3)

#Removing unwanted columns
data.drop(['DISTRICT', 'JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC', 'ANNUAL'], axis=1)

#Summing the sliced columns and storing it in another variable
df = data.groupby(["STATE_UT_NAME"])['Jan-Feb', 'Mar-May', 'Jun-Sep', 'Oct-Dec'].sum()

df

#Selecting the required states 
dt = df.iloc[-9:]

#Resetting index
dt= dt.reset_index()

#Correcting the wrong column names
dt.rename(columns={'level_0	':'State Name'})

#Transposing the data
dt = dt.T

#Defining the function for the plot
def lin_graph(lineg):
    #Setting the figure size
    plt.figure()

    #Plotting the graph
    plt.plot(lineg["STATE_UT_NAME"], lineg["Jan-Feb"], label="Jan-Feb")
    plt.plot(lineg["STATE_UT_NAME"], lineg["Mar-May"], label="Mar-May")
    plt.plot(lineg["STATE_UT_NAME"], lineg["Jun-Sep"], label="Jun-Sep")
    plt.plot(lineg["STATE_UT_NAME"], lineg["Oct-Dec"], label="Oct=Dec")

    #Labelling the data
    plt.xlabel("Year")
    plt.ylabel("Mobile Subscription(weighted Average)")
    plt.title("MOBILE CELLULAR SUBSCRIPTION")

    plt.legend()
    plt.show()

    lin_graph(dt)



